language: python
os: linux
dist: xenial
cache: pip
python:
  - 2.7
  - 3.6
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest pytest-cov
script:
  - cd tests
  - pytest --cov=./
after_success:
  - python -m codecov
