language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
os: linux
dist: xenial
cache: pip
install:
  - pip install pytest
  - pip install coverage
before_script:
    cd tests
script:
  - pytest test_1.py
  - coverage run -m pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
